import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ProPsique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Link className="home-link" href="/">
          <h1>ProPsique</h1>
        </Link>
      </div>

      <ul>
        <Link className="home-link" href="/about">
          <>Sobre mí</>
        </Link>
      </ul>

      <ul>
        <Link className="home-link" href="/contactForm">
          <>Contacta con nosotros</>
        </Link>
      </ul>

      <Image src="/byn.JPG" alt="prueba" width={250} height={300} />

    </>
  );
}
